[pointer_interceptor] Remove `implements` from app-facing package (#6699)
Dart unit tests started failing for `pointer_interceptor` due to the `implements` tag in the app facing package. This plugin is federated for ios and web, so it looks like the error message is valid.

```
Plugin pointer_interceptor:ios provides an implementation for pointer_interceptor_platform_interface and also references a default implementation for pointer_interceptor_ios, which is currently not supported. Ask the maintainers of pointer_interceptor to either remove the implementation via `implements: pointer_interceptor_platform_interface` or avoid referencing a default implementation via `platforms: ios: default_package: pointer_interceptor_ios`.

00:00 +0 -1: loading /b/s/w/ir/x/w/packages/packages/pointer_interceptor/pointer_interceptor/test/tests_exist_elsewhere_test.dart [E]                                                                  
  Error: Please resolve the plugin pubspec errors
  package:flutter_tools/src/base/common.dart 10:3          throwToolExit
  package:flutter_tools/src/flutter_plugins.dart 1214:5    resolvePlatformImplementation
  package:flutter_tools/src/flutter_plugins.dart 1418:55   generateMainDartWithPluginRegistrant
  ===== asynchronous gap ===========================
  package:flutter_tools/src/test/test_compiler.dart 163:9  TestCompiler._onCompilationRequest
  
  TimeoutException after 0:12:00.000000: Test timed out after 12 minutes.
  package:test_api/src/backend/invoker.dart 338:28  Invoker._handleError.<fn>
  dart:async/zone.dart 1391:47                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 336:10  Invoker._handleError
  package:test_api/src/backend/invoker.dart 291:9   Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1399:13                      _rootRun
  dart:async/zone.dart 1301:19                      _CustomZone.run
  package:test_api/src/backend/invoker.dart 290:38  Invoker.heartbeat.<fn>
  dart:async-patch/timer_patch.dart 18:15           Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19         _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5          _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 184:12      _RawReceivePort._handleMessage
  
To run this test again: /b/s/w/ir/x/w/flutter/bin/cache/dart-sdk/bin/dart test 
```

This removes the tag and does a manual roll.