Bump `path_provider_android` to `^2.2.5` due to Android v1 embedder. (#7935)
https://github.com/flutter/engine/pull/52022 removed the Android v1 embedder.

I'm seeing locally that older versions of `path_provider_android` fail due to missing symbols:
```txt
flutter run                   
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/to/flutter-gradle-plugin-apply

Warning: This project is still reading the deprecated '.flutter-plugins. file.
In an upcoming stable release support for this file will be completely removed and your build will fail.
See https:/flutter.dev/to/flutter-plugins-configuration.
/Users/matanl/.pub-cache/hosted/pub.dev/path_provider_android-2.2.2/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java:39: error: cannot find symbol
      @NonNull io.flutter.plugin.common.PluginRegistry.Registrar registrar) {
                                                      ^
  symbol:   class Registrar
  location: interface PluginRegistry
1 error

FAILURE: Build failed with an exception.
```

To be a good citizen, let's make sure users of `path_provider` get a good `path_provider_android`.